site_name: Minima.l
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - bash
        - c
        - lisp
nav:
    - Home: index.md
    - Manual:
        - Language: manual/Language.md
        - Interpreter: manual/Interpreter.md
        - Plugins: manual/Plugins.md
        - Reference: manual/Reference.md
    - Notes:
        - Closures: notes/Closures.md
        - Continuations: notes/Continuations.md
        - "Type Inference": notes/Inference.md
